# Author : Jordan Dennis
# Date : 29/06/2022
# Title : automated_tests.yml
# Description : Automatically runs tests when branches are merged.
#   The tests that are run can be found in the tests directory.

name: automated tests
on: [push]

jobs:
    build:
        name: automated tests
        runs-on: ubuntu-20.04
        steps:
            - name: checkout
              uses: actions/checkout@master

            - name: python
              uses: actions/setup-python@v1
              with:
                python-version: 3.10
                architecture: x64

            - name: install environment
              run: |
                python -m pip install --upgrade pip
                pip install --quiet pytest
                pip install -r --quiet requirements.txt
                pip install --quiet .

            - name: run tests
              run: |
                pytest tests/wavefronts.py
            
