# Author: Jordan Dennis 
# Date: 07/07/2022
# Title: documentation.yml
# Description: Automatically generates the docs on a merge.

name: Documentation
on: [push]

jobs:
  documentation:
    runs-on: ubuntu-20.04
    steps: 
      - name: checkout
        uses: actions/checkout@master

      - name: python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.5
          architecture: x64

      - name: install environment
        run: |
          pip install mkdocs
          pip install mkdocstrings
          pip install mkdocstrings[python]
          pip install mkdocs-material 
          pip install mkdocs-jupyter

      - name: generate documentation
        run: mkdocs gh-deploy -d https://louisdesdoigts.github.io/dLux

